/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayPreviewRouteImport } from './routes/today-preview'
import { Route as SundayScheduleRouteImport } from './routes/sunday-schedule'
import { Route as SundayCheckinRouteImport } from './routes/sunday-checkin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignageRouteImport } from './routes/signage'
import { Route as ServeApplyRouteImport } from './routes/serve-apply'
import { Route as RetreatRegisterRouteImport } from './routes/retreat-register'
import { Route as RetreatInfoRouteImport } from './routes/retreat-info'
import { Route as RetreatHighlightsRouteImport } from './routes/retreat-highlights'
import { Route as RetreatEditRouteImport } from './routes/retreat-edit'
import { Route as RetreatAdminRouteImport } from './routes/retreat-admin'
import { Route as RetreatRouteImport } from './routes/retreat'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MessageBoardRouteImport } from './routes/message-board'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeEditorRouteImport } from './routes/home-editor'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FellowshipCheckinRouteImport } from './routes/fellowship-checkin'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DataPreviewRouteImport } from './routes/data-preview'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodayPublicTokenRouteImport } from './routes/today-public.$token'
import { Route as DisplaySlugRouteImport } from './routes/display.$slug'
import { Route as AdultCheckinKindRouteImport } from './routes/adult-checkin.$kind'
import { Route as DisplayPosterIdRouteImport } from './routes/display.poster.$id'
import { Route as ApiAdminInstallPackageRouteImport } from './routes/api/admin/install-package'

const TodayPreviewRoute = TodayPreviewRouteImport.update({
  id: '/today-preview',
  path: '/today-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayScheduleRoute = SundayScheduleRouteImport.update({
  id: '/sunday-schedule',
  path: '/sunday-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayCheckinRoute = SundayCheckinRouteImport.update({
  id: '/sunday-checkin',
  path: '/sunday-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignageRoute = SignageRouteImport.update({
  id: '/signage',
  path: '/signage',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeApplyRoute = ServeApplyRouteImport.update({
  id: '/serve-apply',
  path: '/serve-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatRegisterRoute = RetreatRegisterRouteImport.update({
  id: '/retreat-register',
  path: '/retreat-register',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatInfoRoute = RetreatInfoRouteImport.update({
  id: '/retreat-info',
  path: '/retreat-info',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatHighlightsRoute = RetreatHighlightsRouteImport.update({
  id: '/retreat-highlights',
  path: '/retreat-highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatEditRoute = RetreatEditRouteImport.update({
  id: '/retreat-edit',
  path: '/retreat-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatAdminRoute = RetreatAdminRouteImport.update({
  id: '/retreat-admin',
  path: '/retreat-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatRoute = RetreatRouteImport.update({
  id: '/retreat',
  path: '/retreat',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageBoardRoute = MessageBoardRouteImport.update({
  id: '/message-board',
  path: '/message-board',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeEditorRoute = HomeEditorRouteImport.update({
  id: '/home-editor',
  path: '/home-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipCheckinRoute = FellowshipCheckinRouteImport.update({
  id: '/fellowship-checkin',
  path: '/fellowship-checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DataPreviewRoute = DataPreviewRouteImport.update({
  id: '/data-preview',
  path: '/data-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayPublicTokenRoute = TodayPublicTokenRouteImport.update({
  id: '/today-public/$token',
  path: '/today-public/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplaySlugRoute = DisplaySlugRouteImport.update({
  id: '/display/$slug',
  path: '/display/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultCheckinKindRoute = AdultCheckinKindRouteImport.update({
  id: '/adult-checkin/$kind',
  path: '/adult-checkin/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayPosterIdRoute = DisplayPosterIdRouteImport.update({
  id: '/display/poster/$id',
  path: '/display/poster/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInstallPackageRoute = ApiAdminInstallPackageRouteImport.update({
  id: '/api/admin/install-package',
  path: '/api/admin/install-package',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/data-preview': typeof DataPreviewRoute
  '/feedback': typeof FeedbackRoute
  '/fellowship-checkin': typeof FellowshipCheckinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home-editor': typeof HomeEditorRoute
  '/login': typeof LoginRoute
  '/message-board': typeof MessageBoardRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retreat': typeof RetreatRoute
  '/retreat-admin': typeof RetreatAdminRoute
  '/retreat-edit': typeof RetreatEditRoute
  '/retreat-highlights': typeof RetreatHighlightsRoute
  '/retreat-info': typeof RetreatInfoRoute
  '/retreat-register': typeof RetreatRegisterRoute
  '/serve-apply': typeof ServeApplyRoute
  '/signage': typeof SignageRoute
  '/signup': typeof SignupRoute
  '/sunday-checkin': typeof SundayCheckinRoute
  '/sunday-schedule': typeof SundayScheduleRoute
  '/today-preview': typeof TodayPreviewRoute
  '/adult-checkin/$kind': typeof AdultCheckinKindRoute
  '/display/$slug': typeof DisplaySlugRoute
  '/today-public/$token': typeof TodayPublicTokenRoute
  '/api/admin/install-package': typeof ApiAdminInstallPackageRoute
  '/display/poster/$id': typeof DisplayPosterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/data-preview': typeof DataPreviewRoute
  '/feedback': typeof FeedbackRoute
  '/fellowship-checkin': typeof FellowshipCheckinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home-editor': typeof HomeEditorRoute
  '/login': typeof LoginRoute
  '/message-board': typeof MessageBoardRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retreat': typeof RetreatRoute
  '/retreat-admin': typeof RetreatAdminRoute
  '/retreat-edit': typeof RetreatEditRoute
  '/retreat-highlights': typeof RetreatHighlightsRoute
  '/retreat-info': typeof RetreatInfoRoute
  '/retreat-register': typeof RetreatRegisterRoute
  '/serve-apply': typeof ServeApplyRoute
  '/signage': typeof SignageRoute
  '/signup': typeof SignupRoute
  '/sunday-checkin': typeof SundayCheckinRoute
  '/sunday-schedule': typeof SundayScheduleRoute
  '/today-preview': typeof TodayPreviewRoute
  '/adult-checkin/$kind': typeof AdultCheckinKindRoute
  '/display/$slug': typeof DisplaySlugRoute
  '/today-public/$token': typeof TodayPublicTokenRoute
  '/api/admin/install-package': typeof ApiAdminInstallPackageRoute
  '/display/poster/$id': typeof DisplayPosterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/data-preview': typeof DataPreviewRoute
  '/feedback': typeof FeedbackRoute
  '/fellowship-checkin': typeof FellowshipCheckinRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home-editor': typeof HomeEditorRoute
  '/login': typeof LoginRoute
  '/message-board': typeof MessageBoardRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retreat': typeof RetreatRoute
  '/retreat-admin': typeof RetreatAdminRoute
  '/retreat-edit': typeof RetreatEditRoute
  '/retreat-highlights': typeof RetreatHighlightsRoute
  '/retreat-info': typeof RetreatInfoRoute
  '/retreat-register': typeof RetreatRegisterRoute
  '/serve-apply': typeof ServeApplyRoute
  '/signage': typeof SignageRoute
  '/signup': typeof SignupRoute
  '/sunday-checkin': typeof SundayCheckinRoute
  '/sunday-schedule': typeof SundayScheduleRoute
  '/today-preview': typeof TodayPreviewRoute
  '/adult-checkin/$kind': typeof AdultCheckinKindRoute
  '/display/$slug': typeof DisplaySlugRoute
  '/today-public/$token': typeof TodayPublicTokenRoute
  '/api/admin/install-package': typeof ApiAdminInstallPackageRoute
  '/display/poster/$id': typeof DisplayPosterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/data-preview'
    | '/feedback'
    | '/fellowship-checkin'
    | '/forgot-password'
    | '/home-editor'
    | '/login'
    | '/message-board'
    | '/register'
    | '/reset-password'
    | '/retreat'
    | '/retreat-admin'
    | '/retreat-edit'
    | '/retreat-highlights'
    | '/retreat-info'
    | '/retreat-register'
    | '/serve-apply'
    | '/signage'
    | '/signup'
    | '/sunday-checkin'
    | '/sunday-schedule'
    | '/today-preview'
    | '/adult-checkin/$kind'
    | '/display/$slug'
    | '/today-public/$token'
    | '/api/admin/install-package'
    | '/display/poster/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/data-preview'
    | '/feedback'
    | '/fellowship-checkin'
    | '/forgot-password'
    | '/home-editor'
    | '/login'
    | '/message-board'
    | '/register'
    | '/reset-password'
    | '/retreat'
    | '/retreat-admin'
    | '/retreat-edit'
    | '/retreat-highlights'
    | '/retreat-info'
    | '/retreat-register'
    | '/serve-apply'
    | '/signage'
    | '/signup'
    | '/sunday-checkin'
    | '/sunday-schedule'
    | '/today-preview'
    | '/adult-checkin/$kind'
    | '/display/$slug'
    | '/today-public/$token'
    | '/api/admin/install-package'
    | '/display/poster/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/data-preview'
    | '/feedback'
    | '/fellowship-checkin'
    | '/forgot-password'
    | '/home-editor'
    | '/login'
    | '/message-board'
    | '/register'
    | '/reset-password'
    | '/retreat'
    | '/retreat-admin'
    | '/retreat-edit'
    | '/retreat-highlights'
    | '/retreat-info'
    | '/retreat-register'
    | '/serve-apply'
    | '/signage'
    | '/signup'
    | '/sunday-checkin'
    | '/sunday-schedule'
    | '/today-preview'
    | '/adult-checkin/$kind'
    | '/display/$slug'
    | '/today-public/$token'
    | '/api/admin/install-package'
    | '/display/poster/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  DataPreviewRoute: typeof DataPreviewRoute
  FeedbackRoute: typeof FeedbackRoute
  FellowshipCheckinRoute: typeof FellowshipCheckinRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeEditorRoute: typeof HomeEditorRoute
  LoginRoute: typeof LoginRoute
  MessageBoardRoute: typeof MessageBoardRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RetreatRoute: typeof RetreatRoute
  RetreatAdminRoute: typeof RetreatAdminRoute
  RetreatEditRoute: typeof RetreatEditRoute
  RetreatHighlightsRoute: typeof RetreatHighlightsRoute
  RetreatInfoRoute: typeof RetreatInfoRoute
  RetreatRegisterRoute: typeof RetreatRegisterRoute
  ServeApplyRoute: typeof ServeApplyRoute
  SignageRoute: typeof SignageRoute
  SignupRoute: typeof SignupRoute
  SundayCheckinRoute: typeof SundayCheckinRoute
  SundayScheduleRoute: typeof SundayScheduleRoute
  TodayPreviewRoute: typeof TodayPreviewRoute
  AdultCheckinKindRoute: typeof AdultCheckinKindRoute
  DisplaySlugRoute: typeof DisplaySlugRoute
  TodayPublicTokenRoute: typeof TodayPublicTokenRoute
  ApiAdminInstallPackageRoute: typeof ApiAdminInstallPackageRoute
  DisplayPosterIdRoute: typeof DisplayPosterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today-preview': {
      id: '/today-preview'
      path: '/today-preview'
      fullPath: '/today-preview'
      preLoaderRoute: typeof TodayPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-schedule': {
      id: '/sunday-schedule'
      path: '/sunday-schedule'
      fullPath: '/sunday-schedule'
      preLoaderRoute: typeof SundayScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday-checkin': {
      id: '/sunday-checkin'
      path: '/sunday-checkin'
      fullPath: '/sunday-checkin'
      preLoaderRoute: typeof SundayCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signage': {
      id: '/signage'
      path: '/signage'
      fullPath: '/signage'
      preLoaderRoute: typeof SignageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve-apply': {
      id: '/serve-apply'
      path: '/serve-apply'
      fullPath: '/serve-apply'
      preLoaderRoute: typeof ServeApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreat-register': {
      id: '/retreat-register'
      path: '/retreat-register'
      fullPath: '/retreat-register'
      preLoaderRoute: typeof RetreatRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreat-info': {
      id: '/retreat-info'
      path: '/retreat-info'
      fullPath: '/retreat-info'
      preLoaderRoute: typeof RetreatInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreat-highlights': {
      id: '/retreat-highlights'
      path: '/retreat-highlights'
      fullPath: '/retreat-highlights'
      preLoaderRoute: typeof RetreatHighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreat-edit': {
      id: '/retreat-edit'
      path: '/retreat-edit'
      fullPath: '/retreat-edit'
      preLoaderRoute: typeof RetreatEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreat-admin': {
      id: '/retreat-admin'
      path: '/retreat-admin'
      fullPath: '/retreat-admin'
      preLoaderRoute: typeof RetreatAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreat': {
      id: '/retreat'
      path: '/retreat'
      fullPath: '/retreat'
      preLoaderRoute: typeof RetreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message-board': {
      id: '/message-board'
      path: '/message-board'
      fullPath: '/message-board'
      preLoaderRoute: typeof MessageBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-editor': {
      id: '/home-editor'
      path: '/home-editor'
      fullPath: '/home-editor'
      preLoaderRoute: typeof HomeEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowship-checkin': {
      id: '/fellowship-checkin'
      path: '/fellowship-checkin'
      fullPath: '/fellowship-checkin'
      preLoaderRoute: typeof FellowshipCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-preview': {
      id: '/data-preview'
      path: '/data-preview'
      fullPath: '/data-preview'
      preLoaderRoute: typeof DataPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today-public/$token': {
      id: '/today-public/$token'
      path: '/today-public/$token'
      fullPath: '/today-public/$token'
      preLoaderRoute: typeof TodayPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$slug': {
      id: '/display/$slug'
      path: '/display/$slug'
      fullPath: '/display/$slug'
      preLoaderRoute: typeof DisplaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult-checkin/$kind': {
      id: '/adult-checkin/$kind'
      path: '/adult-checkin/$kind'
      fullPath: '/adult-checkin/$kind'
      preLoaderRoute: typeof AdultCheckinKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/poster/$id': {
      id: '/display/poster/$id'
      path: '/display/poster/$id'
      fullPath: '/display/poster/$id'
      preLoaderRoute: typeof DisplayPosterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/install-package': {
      id: '/api/admin/install-package'
      path: '/api/admin/install-package'
      fullPath: '/api/admin/install-package'
      preLoaderRoute: typeof ApiAdminInstallPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  DataPreviewRoute: DataPreviewRoute,
  FeedbackRoute: FeedbackRoute,
  FellowshipCheckinRoute: FellowshipCheckinRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeEditorRoute: HomeEditorRoute,
  LoginRoute: LoginRoute,
  MessageBoardRoute: MessageBoardRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RetreatRoute: RetreatRoute,
  RetreatAdminRoute: RetreatAdminRoute,
  RetreatEditRoute: RetreatEditRoute,
  RetreatHighlightsRoute: RetreatHighlightsRoute,
  RetreatInfoRoute: RetreatInfoRoute,
  RetreatRegisterRoute: RetreatRegisterRoute,
  ServeApplyRoute: ServeApplyRoute,
  SignageRoute: SignageRoute,
  SignupRoute: SignupRoute,
  SundayCheckinRoute: SundayCheckinRoute,
  SundayScheduleRoute: SundayScheduleRoute,
  TodayPreviewRoute: TodayPreviewRoute,
  AdultCheckinKindRoute: AdultCheckinKindRoute,
  DisplaySlugRoute: DisplaySlugRoute,
  TodayPublicTokenRoute: TodayPublicTokenRoute,
  ApiAdminInstallPackageRoute: ApiAdminInstallPackageRoute,
  DisplayPosterIdRoute: DisplayPosterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
